{% set version = "2.0.0" %}

package:
    name: pycsw
    version: {{ version }}

source:
    fn: pycsw-{{ version }}.tar.gz
    url: https://github.com/geopython/pycsw/archive/{{ version }}.tar.gz
    sha256: 64c672bb2dfdf7fc9313d01a63bf926ef5a1d251f7a0527de9c32ed38426b83a

build:
    number: 0
    script: python setup.py install
    preserve_egg_dir: True

requirements:
    build:
        - python
    run:
        - python
        - sqlalchemy
        - geolinks
        - lxml
        - owslib
        - pyproj
        - shapely

test:
    imports:
        - pycsw

about:
    home: https://github.com/geopython/pycsw
    license: MIT
    summary: OGC Catalog Service for the Web (CSW) implementation in python

extra:
    recipe-maintainers:
        - ocefpaf
